name: Build

on:
  workflow_run:
    workflows: Test
    branches: main
    # tags: v[\d.]+
    types: completed

env:
  PYCURL_SSL_LIBRARY: openssl
  default_python_version: "3.10"
  PYLOAD_BUILD: ${{ github.run_number }}

jobs:
  sdist:
    name: Build source
    if: github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.default_python_version }}

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools

      - name: Build pyLoad
        run: python setup.py -q sdist

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist--${{ github.run_id }}
          path: dist/*.tar.gz

  bdist:
    name: Build binary
    if: github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.default_python_version }}

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools wheel Babel Jinja2

      - name: Build pyLoad
        run: python setup.py -q build_locale bdist_wheel

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist--${{ github.run_id }}
          path: dist/*.whl
