name: Deploy

on:
  workflow_run:
    workflows: Build
    branches: main
    # tags: v[\d.]+
    types: completed

jobs:
  pypi:
    name: Deploy to PyPI
    if: github.event.workflow_run.conclusion == 'success1'

    runs-on: ubuntu-latest

    steps:
      - name: Dump workflow run conclusion
        env:
          WORKFLOW_RUN_CONCLUSION: ${{ github.event.workflow_run.conclusion }}
        run: echo "WORKFLOW_RUN_CONCLUSION $WORKFLOW_RUN_CONCLUSION"

      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build.yml
          name: dist--${{ github.event.workflow_run.id }}
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
